INSERT INTO TB_COZINHA (NOME) VALUES ('Tailandesa');
INSERT INTO TB_COZINHA (NOME) VALUES ('Indiana');

INSERT INTO TB_RESTAURANTE (NOME, TAXA_FRETE) VALUES ('Restaurante 1', 100.0);
INSERT INTO TB_RESTAURANTE (NOME, TAXA_FRETE) VALUES ('Restaurante 2', 50.0);