INSERT INTO TB_COZINHA (ID, NOME) VALUES (1, 'Tailandesa');
INSERT INTO TB_COZINHA (ID, NOME) VALUES (2, 'Indiana');

INSERT INTO TB_RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Restaurante 1', 100.0, 1);
INSERT INTO TB_RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Restaurante 2', 50.0, 1);
INSERT INTO TB_RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Restaurante 3', 150.0, 2);